version: '3'
services:
  psutarchiveapi:
    container_name: psutarchiveapi
    build: 
      context: .
      dockerfile: Dockerfile
    image: psutarchiveapi:development
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: sqlite
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - ${PORT}:${PORT}
    networks:
      - psutarchiveapi
    
networks:
  psutarchiveapi:
    name: Psutarchiveapi
    driver: bridge
