version: '3'
services:
  psutarchiveapi:
    container_name: psutarchiveapi
    build: 
      context: .
      dockerfile: Dockerfile.prod
    image: psutarchiveapi:production
    restart: unless-stopped
    user: root
    environment:
      DATABASE_HOST: psutarchiveapiDB
      NODE_ENV: production
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - ${PORT}:${PORT}
    networks:
      - psutarchiveapi
    depends_on:
      - psutarchiveapiDB
      
  psutarchiveapiDB:
    container_name: psutarchiveapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - psutarchiveapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    networks:
      - psutarchiveapi
      
  psutarchiveapiAdminer:
    container_name: psutarchiveapiAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '${ADMINER_PORT}:${ADMINER_PORT}'
    environment:
      - ADMINER_DEFAULT_SERVER=psutarchiveapiDB
    networks:
      - psutarchiveapi
    depends_on:
      - psutarchiveapiDB

volumes:
  psutarchiveapi-data:

networks:
  psutarchiveapi:
    name: Psutarchiveapi
    driver: bridge
